# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: leader.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'leader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cleader.proto\x12\x06leader\":\n\x11UploadFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\"$\n\x12UploadFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"(\n\x13\x44ownloadFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"<\n\x14\x44ownloadFileResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ile_end\x18\x02 \x01(\x08\x32\xa3\x01\n\rLeaderService\x12\x45\n\nUploadFile\x12\x19.leader.UploadFileRequest\x1a\x1a.leader.UploadFileResponse(\x01\x12K\n\x0c\x44ownloadFile\x12\x1b.leader.DownloadFileRequest\x1a\x1c.leader.DownloadFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=24
  _globals['_UPLOADFILEREQUEST']._serialized_end=82
  _globals['_UPLOADFILERESPONSE']._serialized_start=84
  _globals['_UPLOADFILERESPONSE']._serialized_end=120
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=122
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=162
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=164
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=224
  _globals['_LEADERSERVICE']._serialized_start=227
  _globals['_LEADERSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
