# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x04node\"9\n\x11StoreChunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\"$\n\x12StoreChunkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"(\n\x14RetrieveChunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\":\n\x15RetrieveChunkResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"&\n\x12\x44\x65leteChunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\"%\n\x13\x44\x65leteChunkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8b\x02\n\x0bNodeService\x12?\n\nStoreChunk\x12\x17.node.StoreChunkRequest\x1a\x18.node.StoreChunkResponse\x12H\n\rRetrieveChunk\x12\x1a.node.RetrieveChunkRequest\x1a\x1b.node.RetrieveChunkResponse\x12\x42\n\x0b\x44\x65leteChunk\x12\x18.node.DeleteChunkRequest\x1a\x19.node.DeleteChunkResponse\x12-\n\x04Ping\x12\x11.node.PingRequest\x1a\x12.node.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORECHUNKREQUEST']._serialized_start=20
  _globals['_STORECHUNKREQUEST']._serialized_end=77
  _globals['_STORECHUNKRESPONSE']._serialized_start=79
  _globals['_STORECHUNKRESPONSE']._serialized_end=115
  _globals['_RETRIEVECHUNKREQUEST']._serialized_start=117
  _globals['_RETRIEVECHUNKREQUEST']._serialized_end=157
  _globals['_RETRIEVECHUNKRESPONSE']._serialized_start=159
  _globals['_RETRIEVECHUNKRESPONSE']._serialized_end=217
  _globals['_DELETECHUNKREQUEST']._serialized_start=219
  _globals['_DELETECHUNKREQUEST']._serialized_end=257
  _globals['_DELETECHUNKRESPONSE']._serialized_start=259
  _globals['_DELETECHUNKRESPONSE']._serialized_end=296
  _globals['_PINGREQUEST']._serialized_start=298
  _globals['_PINGREQUEST']._serialized_end=311
  _globals['_PINGRESPONSE']._serialized_start=313
  _globals['_PINGRESPONSE']._serialized_end=344
  _globals['_NODESERVICE']._serialized_start=347
  _globals['_NODESERVICE']._serialized_end=614
# @@protoc_insertion_point(module_scope)
